# Generated by Django 4.1.7 on 2023-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="amount")),
                ("seller", models.CharField(max_length=100, verbose_name="seller")),
                ("date", models.DateField(verbose_name="date")),
                ("number", models.IntegerField(verbose_name="number")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated_on"),
                ),
                (
                    "added_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="added on"),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
    ]
