# Generated by Django 4.1.7 on 2023-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="name"),
        ),
    ]
