# Generated by Django 4.1.7 on 2023-02-18 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0002_alter_club_president"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("location", models.CharField(max_length=100, verbose_name="location")),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated on"),
                ),
                (
                    "location_link",
                    models.URLField(blank=True, verbose_name="location link"),
                ),
                (
                    "front_image",
                    models.URLField(blank=True, verbose_name="front image"),
                ),
                ("attendance_max", models.IntegerField(verbose_name="attendance max")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.club",
                        verbose_name="club",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "added_on",
                    models.DateTimeField(auto_now=True, verbose_name="added on"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("register", "register"), ("attend", "attendance")],
                        max_length=50,
                        verbose_name="kind",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activity.activity",
                        verbose_name="activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "registration",
                "verbose_name_plural": "registrations",
            },
        ),
    ]
