# Generated by Django 4.1.7 on 2023-02-18 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="image/upload/v1676716777/qe8vfjfudtc8pti3iz3l.png",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
