# Generated by Django 4.1.7 on 2023-02-18 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_club_image_alter_club_header_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="header_image",
            field=cloudinary.models.CloudinaryField(
                default="image/upload/v1676716777/qe8vfjfudtc8pti3iz3l.png",
                max_length=255,
                verbose_name="header image",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                default="image/upload/v1676716777/qe8vfjfudtc8pti3iz3l.png",
                max_length=255,
                verbose_name="logo",
            ),
        ),
    ]
