# Generated by Django 4.1.7 on 2023-02-18 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_club_facebook_link_club_instagram_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                default="image/upload/v1676716777/qe8vfjfudtc8pti3iz3l.png",
                max_length=255,
                verbose_name="profile picture",
            ),
        ),
    ]
